# Generated by Django 2.1.1 on 2018-11-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='place id')),
                ('name', models.CharField(max_length=250, verbose_name='place name')),
                ('description', models.CharField(max_length=1000, verbose_name='description of a place')),
                ('category', models.CharField(max_length=20, verbose_name='category of a place')),
            ],
        ),
    ]
