# Generated by Django 2.1.1 on 2018-11-09 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='event id')),
                ('name', models.CharField(max_length=250, verbose_name='place name')),
                ('description', models.CharField(max_length=2000, verbose_name='description of an event')),
                ('date', models.DateTimeField(verbose_name='time of an event')),
                ('photo', models.ImageField(upload_to='', verbose_name='image of an event')),
                ('link', models.CharField(max_length=100, verbose_name='link to an event or tickets')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='news id')),
                ('content', models.CharField(max_length=1000, verbose_name='content of news')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='photo id')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='photos',
            field=models.ManyToManyField(blank=True, to='content.Photo', verbose_name='photos to news'),
        ),
    ]
