# Generated by Django 2.1 on 2018-11-09 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='time period id')),
                ('time_from', models.DateTimeField(verbose_name='time the event takes place from')),
                ('time_to', models.DateTimeField(verbose_name='time the event finishes')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, max_length=100, verbose_name='link to an event or tickets'),
        ),
        migrations.AddField(
            model_name='event',
            name='dates',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.TimePeriod', verbose_name='dates the event takes place on'),
        ),
    ]
